//ARMAZENAR AS NOTAS DA PROVA DE UMA TURMA DE 15 ESTUDANTES;
// AS NOTAS SÃO FORNECIDAS PELO USUARIO E DEVEM PERTENCER AO INTERVALO [0..10].
//AS EVENTUAIS TENTATIVAS DE ENTRADA DE DADOS INVÁLIDOS DEVEM SER IGNORADAS;
// A NOTA SUFICIENTE PARA APROVAÇÃO É 6;
//O ALUNO TERÁ DIREITO A UMA NOVA AVALIAÇÃO SE TIVER A NOTA ENTRE 3,5 E 5,5.
// O PROGRAMA DEVE CALCULAR: QUANTOS ALUNOS FORAM, APROVADOS NA PROVA;
// QUANTOS ALUNOS TERÃO DIREITO A UMA NOVA AVALIAÇÃO;
//QUANTOS ALUNOS FORAM REPROVADOS;
//NOTA MEDIA DOS ALUNOS APROVADOS;
#include<stdio.h>
int main()
{

    for(i=0;i<0;i++)
    {
        printf("Digite a nota%i")
    }
}
